# Generated by Django 4.0.1 on 2022-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('founded_on', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('head_count', models.IntegerField()),
            ],
        ),
    ]
