# Generated by Django 4.0.1 on 2022-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_branch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
